### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by mutdmour** [bitomule/simple-metacrawler#4]
getting this error

```
While loading package bitomule:simple-metacrawler@0.2.7:
error: Command failed:
/Users/mutasemdmour/.meteor/packages/meteor-tool/.1.4.1_1.1hmmdan++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
In file included from ../src/binding.cc:18:
In file included from ../../../../iconv/node_modules/nan/nan.h:74:
In file included from ../../../../iconv/node_modules/nan/nan_new.h:190:
../../../../iconv/node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many arguments to function call, expected at
most 2, have 4
return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/v8.h:4675:3: note: 'New' declared here
static Local<Signature> New(
^
In file included from ../src/binding.cc:18:
../../../../iconv/node_modules/nan/nan.h:165:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:160:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:310:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:315:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(NanNew(v8::Null(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:320:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:325:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(NanNew(v8::False(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:557:13: error: no member named 'smalloc' in namespace 'node'
, node::smalloc::FreeCallback callback
~~~~~~^
../../../../iconv/node_modules/nan/nan.h:568:12: error: no matching function for call to 'New'
return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
^~~~~~~~~~~~~~~~~
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/node_buffer.h:34:40: note: candidate function not viable: no known conversion
from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
^
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/node_buffer.h:46:40: note: candidate function not viable: 2nd argument ('const
char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
^
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/node_buffer.h:31:40: note: candidate function not viable: requires 2 arguments,
but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
^
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/node_buffer.h:39:40: note: candidate function not viable: requires 5 arguments,
but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
^
In file included from ../src/binding.cc:18:
../../../../iconv/node_modules/nan/nan.h:572:12: error: no viable conversion from returned value of type
'v8::MaybeLocal<v8::Object>' to function return type 'v8::Local<v8::Object>'
return node::Buffer::New(v8::Isolate::GetCurrent(), size);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not
viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
^
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not
viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against
'MaybeLocal'
V8_INLINE Local(Local<S> that)
^
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against
'v8::MaybeLocal<v8::Object>'
V8_INLINE Local(S* that)
^
In file included from ../src/binding.cc:18:
../../../../iconv/node_modules/nan/nan.h:579:26: error: no member named 'Use' in namespace 'node::Buffer'
return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
~~~~~~~~~~~~~~^
../../../../iconv/node_modules/nan/nan.h:1396:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Function]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:1411:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(node::MakeCallback(
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Value]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:1484:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Object]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../src/binding.cc:99:31: error: no member named 'GetIndexedPropertiesExternalArrayData' in 'v8::Object'
args[1].As<Object>()->GetIndexedPropertiesExternalArrayData());
~~~~~~~~~~~~~~~~~~~~  ^
../src/binding.cc:103:31: error: no member named 'GetIndexedPropertiesExternalArrayData' in 'v8::Object'
args[4].As<Object>()->GetIndexedPropertiesExternalArrayData());
~~~~~~~~~~~~~~~~~~~~  ^
15 errors generated.
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/Users/mutasemdmour/.meteor/packages/meteor-tool/.1.4.1_1.1hmmdan++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command
"/Users/mutasemdmour/.meteor/packages/meteor-tool/.1.4.1_1.1hmmdan++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/mutasemdmour/.meteor/packages/meteor-tool/.1.4.1_1.1hmmdan++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/Users/mutasemdmour/.meteor/packages/bitomule_simple-metacrawler/.0.2.7.17ochgk++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-cn6hur/node_modules/iconv
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Darwin 15.6.0
npm ERR! argv
"/Users/mutasemdmour/.meteor/packages/meteor-tool/.1.4.1_1.1hmmdan++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/mutasemdmour/.meteor/packages/meteor-tool/.1.4.1_1.1hmmdan++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! iconv@2.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.1.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/mutasemdmour/.meteor/packages/bitomule_simple-metacrawler/.0.2.7.17ochgk++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-cn6hur/npm-debug.log
In file included from ../src/binding.cc:18:
In file included from ../../../../iconv/node_modules/nan/nan.h:74:
In file included from ../../../../iconv/node_modules/nan/nan_new.h:190:
../../../../iconv/node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many arguments to function call, expected at
most 2, have 4
return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/v8.h:4675:3: note: 'New' declared here
static Local<Signature> New(
^
In file included from ../src/binding.cc:18:
../../../../iconv/node_modules/nan/nan.h:165:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:160:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:310:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:315:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(NanNew(v8::Null(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:320:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:325:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(NanNew(v8::False(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:557:13: error: no member named 'smalloc' in namespace 'node'
, node::smalloc::FreeCallback callback
~~~~~~^
../../../../iconv/node_modules/nan/nan.h:568:12: error: no matching function for call to 'New'
return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
^~~~~~~~~~~~~~~~~
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/node_buffer.h:34:40: note: candidate function not viable: no known conversion
from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
^
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/node_buffer.h:46:40: note: candidate function not viable: 2nd argument ('const
char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
^
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/node_buffer.h:31:40: note: candidate function not viable: requires 2 arguments,
but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
^
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/node_buffer.h:39:40: note: candidate function not viable: requires 5 arguments,
but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
^
In file included from ../src/binding.cc:18:
../../../../iconv/node_modules/nan/nan.h:572:12: error: no viable conversion from returned value of type
'v8::MaybeLocal<v8::Object>' to function return type 'v8::Local<v8::Object>'
return node::Buffer::New(v8::Isolate::GetCurrent(), size);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not
viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
^
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not
viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against
'MaybeLocal'
V8_INLINE Local(Local<S> that)
^
/Users/mutasemdmour/.node-gyp/4.5.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against
'v8::MaybeLocal<v8::Object>'
V8_INLINE Local(S* that)
^
In file included from ../src/binding.cc:18:
../../../../iconv/node_modules/nan/nan.h:579:26: error: no member named 'Use' in namespace 'node::Buffer'
return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
~~~~~~~~~~~~~~^
../../../../iconv/node_modules/nan/nan.h:1396:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Function]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:1411:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(node::MakeCallback(
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Value]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../../../../iconv/node_modules/nan/nan.h:1484:12: error: no matching function for call to '_NanEnsureLocal'
return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:296:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
^~~~~~~~~~~~~~~
../../../../iconv/node_modules/nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Object]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
^
../src/binding.cc:99:31: error: no member named 'GetIndexedPropertiesExternalArrayData' in 'v8::Object'
args[1].As<Object>()->GetIndexedPropertiesExternalArrayData());
~~~~~~~~~~~~~~~~~~~~  ^
../src/binding.cc:103:31: error: no member named 'GetIndexedPropertiesExternalArrayData' in 'v8::Object'
args[4].As<Object>()->GetIndexedPropertiesExternalArrayData());
~~~~~~~~~~~~~~~~~~~~  ^
15 errors generated.
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/Users/mutasemdmour/.meteor/packages/meteor-tool/.1.4.1_1.1hmmdan++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command
"/Users/mutasemdmour/.meteor/packages/meteor-tool/.1.4.1_1.1hmmdan++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/mutasemdmour/.meteor/packages/meteor-tool/.1.4.1_1.1hmmdan++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/Users/mutasemdmour/.meteor/packages/bitomule_simple-metacrawler/.0.2.7.17ochgk++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-cn6hur/node_modules/iconv
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Darwin 15.6.0
npm ERR! argv
"/Users/mutasemdmour/.meteor/packages/meteor-tool/.1.4.1_1.1hmmdan++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/mutasemdmour/.meteor/packages/meteor-tool/.1.4.1_1.1hmmdan++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! iconv@2.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.1.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/mutasemdmour/.meteor/packages/bitomule_simple-metacrawler/.0.2.7.17ochgk++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-cn6hur/npm-debug.log
```

**Comment by ruijadom** [comment]
Same happens to me!

**Comment by bitomule** [comment]
I think an update on Meteor broke the package. I'm not using this package anymore, will try to take a look if I can but if anyone finds the issue please create a PR

**Comment by bitomule** [comment]
I think I've fixed just updating dependencies. Please try to install now and report if you find any issues. Thanks!

**Comment by ruijadom** [comment]
Works! Well done! nice job!

**Comment by shaileshsitestrokes** [comment]
getting this error when i run this command "meteor add bitomule:simple-metacrawler" on my windows 10 computer using command prompt
While loading package bitomule:simple-metacrawler@0.2.8:
error: Command failed:
C:\Users\onlighten\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd
rebuild --update-binary
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files
(x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(C:\Users\onlighten\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command
"C:\\Users\\onlighten\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\onlighten\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd
C:\Users\onlighten\AppData\Local\.meteor\packages\bitomule_simple-metacrawler\0.2.8\npm\node_modules\.temp-1spo1id\node_modules\iconv
gyp ERR! node -v v4.6.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.14393
npm ERR! argv
"C:\\Users\\onlighten\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\onlighten\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
"rebuild" "--update-binary"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! iconv@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm
installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
C:\Users\onlighten\AppData\Local\.meteor\packages\bitomule_simple-metacrawler\0.2.8\npm\node_modules\.temp-1spo1id\npm-debug.log
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files
(x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(C:\Users\onlighten\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command
"C:\\Users\\onlighten\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\onlighten\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd
C:\Users\onlighten\AppData\Local\.meteor\packages\bitomule_simple-metacrawler\0.2.8\npm\node_modules\.temp-1spo1id\node_modules\iconv
gyp ERR! node -v v4.6.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.14393
npm ERR! argv
"C:\\Users\\onlighten\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\onlighten\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
"rebuild" "--update-binary"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! iconv@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm
installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
C:\Users\onlighten\AppData\Local\.meteor\packages\bitomule_simple-metacrawler\0.2.8\npm\node_modules\.temp-1spo1id\npm-debug.log
